version: "3.8"
services:
    vnc:
        build:
            context: .
            dockerfile: Dockerfile.Debian
        container_name: vnc
        hostname: vnc
        image: enwaiax/vnc
        privileged: true
        ports:
            - 6901:5901
            - "10022:22"
        restart: unless-stopped
