FROM debian:latest
ENV DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai
RUN apt-get update && apt-get install -y --no-install-recommends \
    tigervnc-standalone-server autocutsel \
    xfce4 xfce4-terminal openssh-server supervisor \
    procps \
    dbus-x11 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
WORKDIR /root
COPY passwd /root/.vnc/
COPY entrypoint.sh /
COPY supervisord.conf /etc/supervisor/conf.d/
EXPOSE 5901 22
ENTRYPOINT [ "/entrypoint.sh" ]